In [1]:
import pandas as pd
import torch

In [2]:
train_df = pd.read_csv("archive/train.csv")
test_df = pd.read_csv("archive/test.csv")
validation_df = pd.read_csv("archive/validation.csv")

In [3]:
train_df.head()
train_df.info()
train_df.isna().sum()
train_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22593 entries, 0 to 22592
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          22593 non-null  int64
 1   NCBIGeneID          22593 non-null  int64
 2   Symbol              22593 non-null  object
 3   Description         22593 non-null  object
 4   GeneType            22593 non-null  object
 5   GeneGroupMethod     22593 non-null  object
 6   NucleotideSequence  22593 non-null  object
dtypes: int64(2), object(5)
memory usage: 1.2+ MB

Unnamed: 0            0
NCBIGeneID            0
Symbol                0
Description           0
GeneType              0
GeneGroupMethod       0
NucleotideSequence    0
dtype: int64

In [4]:
train_df.head()

,Unnamed: 0,NCBIGeneID,Symbol,Description,GeneType,GeneGroupMethod,NucleotideSequence
0,0,106481178,RNU4-21P,"RNA, U4 small nuclear 21, pseudogene",PSEUDO,NCBI Ortholog,<AGCTTAGCACAGTGGCAGTATCATAGGCAGTGAGGTTTATCCGAG...
1,1,123477792,LOC123477792,Sharpr-MPRA regulatory region 12926,BIOLOGICAL_REGION,NCBI Ortholog,<CTGGAGCGGCCACGATGTGAACTGTCACCGGCCACTGCTGCTCCG...
2,2,113174975,LOC113174975,Sharpr-MPRA regulatory region 7591,BIOLOGICAL_REGION,NCBI Ortholog,<TTCCCAATTTTTCCTCTGCTTTTTAATTTTCTAGTTTCCTTTTTC...
3,3,116216107,LOC116216107,CRISPRi-validated cis-regulatory element chr10...,BIOLOGICAL_REGION,NCBI Ortholog,<CGCCCAGGCTGGAGTGCAGTGGCGCCATCTCGGCTCACTGCAGGC...
4,4,28502,IGHD2-21,immunoglobulin heavy diversity 2-21,OTHER,NCBI Ortholog,<AGCATATTGTGGTGGTGACTGCTATTCC>

In [5]:
train_df["Description"].value_counts()

Description
small nucleolar RNA U13                  428
5.8S ribosomal RNA                       171
small nucleolar RNA U3                   106
U2 spliceosomal RNA                       99
5S ribosomal RNA                          86
                                        ...
microRNA 548m                              1
Sharpr-MPRA regulatory region 12117        1
Nanog homeobox pseudogene 6                1
RNA, U6 small nuclear 485, pseudogene      1
Sharpr-MPRA regulatory region 11449        1
Name: count, Length: 21034, dtype: int64

In [6]:
train_df.columns

Index(['Unnamed: 0', 'NCBIGeneID', 'Symbol', 'Description', 'GeneType',
       'GeneGroupMethod', 'NucleotideSequence'],
      dtype='object')

In [7]:
train_df = train_df[["Description","NucleotideSequence"]]

In [8]:
train_df["prefix"] = train_df["Description"].str.extract(r'^([A-Za-z]+)')

In [9]:
train_df["Description"] = train_df["Description"].str.replace(r"[,]", "", regex=True)
train_df["NucleotideSequence"] = train_df["NucleotideSequence"].str.replace(r"[<>]", "", regex=True)

In [10]:
def divide_in_codons(df, sequence_column="NucleotideSequence", new_column="Codons"):
    train_df["Codons"] = train_df[sequence_column].apply(
        lambda tri: [tri[i:i+3] for i in range(0, len(tri), 3)]
    )
    return df

In [11]:
train_df.head()

,Description,NucleotideSequence,prefix
0,RNA U4 small nuclear 21 pseudogene,AGCTTAGCACAGTGGCAGTATCATAGGCAGTGAGGTTTATCCGAGG...,RNA
1,Sharpr-MPRA regulatory region 12926,CTGGAGCGGCCACGATGTGAACTGTCACCGGCCACTGCTGCTCCGA...,Sharpr
2,Sharpr-MPRA regulatory region 7591,TTCCCAATTTTTCCTCTGCTTTTTAATTTTCTAGTTTCCTTTTTCC...,Sharpr
3,CRISPRi-validated cis-regulatory element chr10...,CGCCCAGGCTGGAGTGCAGTGGCGCCATCTCGGCTCACTGCAGGCT...,CRISPRi
4,immunoglobulin heavy diversity 2-21,AGCATATTGTGGTGGTGACTGCTATTCC,immunoglobulin

In [12]:
train_df = divide_in_codons(train_df)

In [ ]:
def map_nucleotides(sequence):
    remaping_DNA = {"A":4,"G":5,"C":6,"T":7}
    return [remaping_DNA[letter] for letter in sequence]

NameError: name 'letter' is not defined

In [31]:
train_df["NucleotideSequence"]

0        AGCTTAGCACAGTGGCAGTATCATAGGCAGTGAGGTTTATCCGAGG...
1        CTGGAGCGGCCACGATGTGAACTGTCACCGGCCACTGCTGCTCCGA...
2        TTCCCAATTTTTCCTCTGCTTTTTAATTTTCTAGTTTCCTTTTTCC...
3        CGCCCAGGCTGGAGTGCAGTGGCGCCATCTCGGCTCACTGCAGGCT...
4                             AGCATATTGTGGTGGTGACTGCTATTCC
                               ...
22588    GGTGGGGTGGGGTGGGGTGGGGTGGGGTGCAGAGAAAACGATTGAT...
22589    GTGCTCACTTCAGCAGCACATATACTAAAATTGGAATGATACAGAG...
22590    GCTGGGCGTGGTGGTGGGTGCCTGTAATCCCAGCTACTAGGGAGGC...
22591    TCGTCCTGAAGCAGCGGCCAGAGAAGAGACAAGGGCACGAGCATCA...
22592    GGGGATGTAGCTCAGTGGTAGAGCGCATGCTTTGCATGTATGAGGC...
Name: NucleotideSequence, Length: 22593, dtype: object

In [14]:
train_df.fillna(0)

,Description,NucleotideSequence,prefix,Codons
0,RNA U4 small nuclear 21 pseudogene,AGCTTAGCACAGTGGCAGTATCATAGGCAGTGAGGTTTATCCGAGG...,RNA,"[AGC, TTA, GCA, CAG, TGG, CAG, TAT, CAT, AGG, ..."
1,Sharpr-MPRA regulatory region 12926,CTGGAGCGGCCACGATGTGAACTGTCACCGGCCACTGCTGCTCCGA...,Sharpr,"[CTG, GAG, CGG, CCA, CGA, TGT, GAA, CTG, TCA, ..."
2,Sharpr-MPRA regulatory region 7591,TTCCCAATTTTTCCTCTGCTTTTTAATTTTCTAGTTTCCTTTTTCC...,Sharpr,"[TTC, CCA, ATT, TTT, CCT, CTG, CTT, TTT, AAT, ..."
3,CRISPRi-validated cis-regulatory element chr10...,CGCCCAGGCTGGAGTGCAGTGGCGCCATCTCGGCTCACTGCAGGCT...,CRISPRi,"[CGC, CCA, GGC, TGG, AGT, GCA, GTG, GCG, CCA, ..."
4,immunoglobulin heavy diversity 2-21,AGCATATTGTGGTGGTGACTGCTATTCC,immunoglobulin,"[AGC, ATA, TTG, TGG, TGG, TGA, CTG, CTA, TTC, C]"
...,...,...,...,...
22588,uncharacterized LOC124907055,GGTGGGGTGGGGTGGGGTGGGGTGGGGTGCAGAGAAAACGATTGAT...,uncharacterized,"[GGT, GGG, GTG, GGG, TGG, GGT, GGG, GTG, GGG, ..."
22589,RNA U6 small nuclear 1060 pseudogene,GTGCTCACTTCAGCAGCACATATACTAAAATTGGAATGATACAGAG...,RNA,"[GTG, CTC, ACT, TCA, GCA, GCA, CAT, ATA, CTA, ..."
22590,RNA 7SL cytoplasmic 387 pseudogene,GCTGGGCGTGGTGGTGGGTGCCTGTAATCCCAGCTACTAGGGAGGC...,RNA,"[GCT, GGG, CGT, GGT, GGT, GGG, TGC, CTG, TAA, ..."
22591,NADH:ubiquinone oxidoreductase subunit S5 pseu...,TCGTCCTGAAGCAGCGGCCAGAGAAGAGACAAGGGCACGAGCATCA...,NADH,"[TCG, TCC, TGA, AGC, AGC, GGC, CAG, AGA, AGA, ..."
22592,tRNA-Ala (anticodon TGC) 3-1,GGGGATGTAGCTCAGTGGTAGAGCGCATGCTTTGCATGTATGAGGC...,tRNA,"[GGG, GAT, GTA, GCT, CAG, TGG, TAG, AGC, GCA, ..."

In [15]:
train_df["words_size"] = train_df["Description"].str.split().apply(lambda words: [len(w) for w in words])

In [16]:
word_lenght = train_df["words_size"].apply(pd.Series).rename(columns= lambda x: f"w_lenght_{x}")
train_df = pd.concat([train_df, word_lenght], axis=1).drop(columns=["words_size"])

In [25]:
def encoder_codons():
    for axes in train_df["Codons"]:
        n_codon = len(axes)
        print(n_codon)

In [26]:
encoder_codons()

42
99
99
92
10
19
32
176
28
35
88
161
35
96
89
299
99
36
31
99
35
99
52
25
39
115
263
99
310
84
20
99
234
99
213
97
304
92
276
35
203
131
36
294
41
99
99
65
24
99
99
99
20
281
99
99
320
19
134
22
99
167
193
24
99
29
222
189
99
99
22
163
333
61
203
322
174
221
82
37
114
39
36
120
99
118
302
242
63
98
123
99
99
37
99
55
250
140
99
99
101
323
99
99
36
212
32
112
21
133
99
99
35
99
24
224
33
105
99
99
132
213
99
99
99
36
36
167
35
99
275
34
99
171
99
30
186
99
97
99
25
224
215
23
52
99
99
27
205
70
41
99
23
243
30
191
28
100
101
292
24
275
30
36
34
99
192
209
99
281
30
99
126
35
99
243
233
107
99
207
99
185
25
99
92
33
99
70
155
49
168
126
125
116
67
30
36
99
28
99
44
25
99
325
74
36
31
103
57
32
24
19
177
36
49
37
21
27
21
249
239
234
25
273
95
99
26
98
210
48
49
221
36
58
206
241
323
127
275
165
8
46
175
100
99
50
273
167
310
28
99
191
99
210
99
72
96
31
217
68
121
40
26
36
314
37
245
31
20
99
25
99
99
99
309
21
80
172
312
321
99
99
35
306
266
118
63
36
24
36
17
244
35
276
36
99
38
26
57
132
173
99
99
99
33
199
20
221
157
87
192
26
267
99
99
255
99
35
16
175
99
277
225
28
99
25
225
99
99
304
171
194
46
306
99
41
49
36
99
162
99
167
99
99
174
28
99
71
220
99
96
328
99
153
165
221
294
99
36
100
134
99
99
25
177
99
133
245
169
201
99
99
34
36
47
27
178
99
99
36
99
288
99
119
21
27
151
73
80
297
99
292
257
228
99
25
83
155
99
36
27
99
28
168
33
14
35
36
27
263
275
98
241
25
99
99
35
99
99
99
99
35
27
296
44
99
99
25
185
155
72
40
99
53
200
308
85
327
132
49
236
99
211
47
226
32
149
265
49
218
28
311
57
37
99
71
40
330
32
99
186
36
24
32
99
48
86
99
105
172
205
319
43
28
99
51
326
310
130
202
113
301
169
135
25
99
99
34
286
183
44
99
223
99
99
25
17
36
171
46
99
175
99
99
72
34
208
34
40
164
329
22
290
38
26
135
99
37
124
34
55
35
99
286
99
262
99
33
49
287
187
99
99
28
99
19
99
99
21
40
99
20
32
40
21
99
99
82
99
99
119
52
55
25
171
60
37
122
99
175
23
34
246
99
49
219
99
38
99
237
31
92
194
35
99
307
28
99
301
39
20
36
233
99
19
36
180
26
99
36
180
99
159
33
99
99
49
19
297
24
193
26
109
22
193
34
215
43
99
125
47
99
99
159
99
216
99
99
92
45
25
117
157
99
99
272
44
99
99
30
99
99
36
99
99
64
278
323
306
29
28
7
99
20
139
99
196
156
261
269
154
35
99
99
99
99
124
181
27
99
99
99
99
305
142
109
25
189
211
28
187
51
318
99
24
42
247
39
99
99
32
107
328
35
99
113
74
99
28
36
27
99
116
129
99
28
54
44
22
290
47
167
99
212
99
99
316
99
99
99
326
99
99
99
99
23
99
99
40
99
176
25
99
99
99
304
99
26
99
95
22
99
176
99
320
28
99
49
235
21
99
178
98
37
49
38
24
20
33
241
161
23
116
190
99
298
43
34
21
99
333
23
24
99
319
99
99
156
185
134
37
286
49
148
56
160
222
321
115
29
99
99
99
99
99
177
55
27
99
244
226
295
149
99
145
35
39
21
178
36
122
24
99
26
99
99
99
230
36
99
133
29
99
99
18
99
24
29
99
193
40
99
36
31
99
314
64
54
327
99
49
28
85
28
68
99
197
20
217
59
268
83
35
99
127
168
99
31
35
29
218
94
99
35
99
25
113
185
73
23
99
34
99
35
6
316
313
99
36
174
27
250
64
132
79
294
99
124
99
99
252
35
157
99
197
99
243
99
259
263
99
35
255
32
287
36
99
274
120
38
36
99
270
99
24
314
99
99
173
314
99
158
39
24
46
99
172
26
98
307
27
120
35
153
281
99
209
99
36
152
258
32
109
159
31
116
209
21
99
99
99
49
99
36
282
99
30
109
99
28
29
26
236
315
22
24
255
99
110
183
154
99
99
145
34
105
264
109
23
115
269
99
224
323
33
28
312
99
99
167
20
133
20
254
126
24
289
172
99
124
99
99
35
99
30
36
196
28
99
35
299
99
99
195
99
34
181
268
210
99
278
33
99
32
235
25
40
36
133
29
175
75
304
233
30
29
54
36
193
21
35
99
20
99
190
99
99
99
99
147
323
44
28
110
176
49
243
99
21
99
304
301
99
92
88
173
23
34
185
258
36
139
99
167
316
99
244
152
99
24
99
99
32
277
309
37
29
99
35
99
230
31
38
24
128
43
325
317
20
25
311
297
99
33
99
109
99
99
181
224
194
29
41
99
30
201
313
99
100
32
24
99
26
27
27
258
97
312
99
36
19
138
99
99
36
156
35
316
92
99
99
99
81
99
130
225
306
187
99
42
21
229
315
99
99
35
99
99
19
99
216
112
327
22
36
34
200
99
26
112
44
200
122
284
25
130
99
71
247
322
99
99
99
303
99
25
112
100
222
99
126
99
123
22
31
99
29
99
99
35
221
247
99
25
99
98
238
44
310
169
293
94
66
99
99
121
35
35
99
64
37
23
25
167
99
28
26
164
28
99
96
123
64
99
99
179
99
36
99
124
69
99
99
29
29
99
99
311
99
49
165
79
21
99
152
41
99
35
99
233
99
230
99
293
260
89
194
99
99
99
169
196
69
21
295
146
24
131
88
34
23
37
20
119
24
311
76
321
97
196
36
308
136
36
134
99
49
99
36
322
100
99
99
194
99
99
99
55
289
99
99
24
99
99
99
169
45
95
49
99
41
99
115
29
125
259
188
24
15
47
288
147
99
20
43
40
99
258
99
211
99
213
115
99
43
201
29
99
167
99
33
134
99
99
45
99
226
99
167
99
221
80
128
99
106
99
319
99
21
36
147
292
155
306
146
34
34
43
88
24
206
261
247
99
184
33
36
7
26
147
46
99
33
99
248
161
99
100
149
25
99
306
44
307
35
24
49
99
99
159
332
45
150
271
99
25
24
99
99
279
21
95
123
143
30
269
29
334
99
99
29
99
99
99
94
24
99
192
44
25
37
195
156
296
99
99
204
237
99
29
99
200
327
200
99
48
99
172
291
23
197
309
99
52
99
46
208
39
27
99
99
99
31
99
99
51
26
35
151
160
15
35
33
19
36
152
21
35
99
99
129
99
170
266
29
20
35
99
40
29
25
99
325
105
99
321
99
158
22
152
29
174
321
99
180
99
99
326
182
195
308
77
45
39
27
99
316
31
204
315
205
34
32
99
30
63
176
99
219
99
100
99
99
49
141
46
99
49
99
61
145
31
119
26
220
87
40
99
29
59
46
28
99
99
314
99
99
47
99
34
199
295
28
198
26
205
99
271
289
11
154
81
26
99
99
293
99
152
99
22
35
99
99
20
99
99
99
234
311
54
49
27
251
99
99
230
46
99
153
159
21
24
100
63
99
326
99
126
98
205
34
318
27
153
165
95
205
180
36
42
205
99
152
135
282
35
99
99
35
99
30
99
20
99
161
37
99
25
32
99
99
99
99
295
99
21
36
99
25
187
35
21
99
99
99
36
26
270
99
36
114
99
91
25
99
303
99
23
30
106
99
185
99
152
27
99
32
63
152
55
32
34
99
269
220
34
332
315
233
86
279
94
35
99
31
99
313
286
99
99
99
99
99
99
216
45
36
266
36
274
31
97
99
18
99
36
99
40
46
99
325
35
127
314
148
99
26
187
118
99
223
72
132
192
35
28
99
274
177
29
150
101
99
317
169
99
241
149
55
99
47
48
29
38
95
131
24
279
99
79
20
99
74
99
116
98
34
40
221
277
100
161
321
99
164
319
99
30
98
99
258
99
28
318
99
117
99
186
99
167
101
110
102
319
156
99
242
99
28
158
99
79
123
164
40
30
97
162
60
326
99
107
36
34
101
155
28
24
44
36
99
99
99
333
151
99
99
99
309
99
288
99
183
76
111
99
35
167
42
54
99
24
177
99
165
80
99
290
310
36
140
99
30
107
99
167
171
99
99
99
35
99
304
30
328
35
31
61
302
25
181
99
99
36
21
278
99
99
174
99
20
172
100
302
164
30
107
199
37
26
25
256
161
225
101
99
108
34
99
40
99
192
153
99
36
99
36
35
206
155
35
153
94
49
99
187
332
172
99
146
220
36
34
37
99
99
99
202
276
160
92
99
223
114
99
83
99
29
99
148
99
99
212
260
180
99
192
275
328
99
81
35
144
50
99
99
35
30
21
103
99
43
36
46
99
218
35
99
207
30
36
34
28
99
99
13
26
218
99
22
99
24
47
215
257
302
83
90
99
167
99
165
170
37
27
99
99
321
99
21
97
326
267
99
323
36
203
194
22
99
99
166
120
175
22
102
99
99
99
99
124
55
27
25
99
24
99
205
26
188
38
56
153
208
99
99
112
99
167
36
28
42
106
21
35
220
168
99
143
227
132
160
99
21
99
35
91
99
99
99
99
99
194
99
228
99
288
165
99
118
187
59
255
208
37
99
33
165
36
198
291
35
282
27
154
203
75
40
146
39
99
99
35
99
99
99
99
99
256
187
121
99
311
210
64
265
28
171
331
227
27
194
99
35
32
99
36
99
99
99
319
99
194
117
148
74
20
332
286
28
334
20
99
23
92
200
30
99
21
154
184
99
197
99
25
23
99
36
257
183
24
99
22
208
25
92
124
99
299
179
99
170
99
177
333
34
170
34
99
268
277
135
43
128
99
20
142
99
101
35
99
99
45
319
23
294
150
306
311
20
25
159
309
35
291
25
99
36
196
175
281
35
99
99
36
66
99
34
259
301
35
99
22
273
99
68
175
85
106
99
27
99
23
99
113
99
52
99
99
99
145
324
180
56
95
210
161
31
27
99
99
42
23
45
243
99
187
300
99
99
99
281
38
42
100
273
99
36
27
99
99
316
99
175
20
219
63
56
212
99
24
21
303
178
21
100
99
55
49
326
96
21
205
299
36
259
160
168
49
308
224
36
315
185
34
99
49
99
99
99
242
68
23
99
183
99
35
105
99
144
21
127
219
35
46
99
99
99
99
325
99
27
34
19
34
99
280
152
99
238
198
99
99
99
23
30
32
318
99
99
35
35
99
329
207
258
46
25
36
99
99
260
99
100
75
99
111
20
35
263
247
36
230
99
99
200
156
61
159
133
329
43
104
25
99
245
99
35
107
99
36
33
31
214
24
37
294
182
99
99
99
25
33
275
89
25
99
99
65
31
191
91
175
105
22
200
99
145
99
99
96
160
91
55
22
99
295
99
185
174
99
99
235
52
99
140
301
217
225
33
36
66
99
226
99
105
261
99
224
84
229
227
42
161
99
212
208
99
158
202
35
253
156
96
96
145
62
99
314
99
285
238
293
158
174
307
49
20
121
332
99
102
28
99
186
20
38
308
184
24
162
40
43
151
202
269
35
135
99
258
36
220
164
21
99
25
30
256
35
99
121
33
270
250
88
85
175
99
99
63
99
206
199
99
117
35
41
216
27
292
52
314
80
54
39
318
99
21
30
99
193
194
146
125
99
99
218
180
309
307
99
62
334
172
99
247
204
147
99
250
224
134
99
87
48
99
236
99
99
22
163
320
13
99
1
99
200
51
99
99
49
19
99
27
39
100
135
99
99
49
313
155
319
99
19
25
35
105
99
36
33
187
135
93
99
99
177
99
118
250
117
99
255
99
98
186
177
36
99
202
111
99
24
37
99
25
99
22
99
260
36
227
221
183
99
197
20
99
49
99
36
42
150
99
99
236
312
99
99
101
313
62
26
329
63
215
99
99
167
99
228
224
99
117
56
117
36
239
37
21
269
99
25
98
36
99
278
115
64
29
35
216
44
95
37
108
189
97
255
38
161
173
180
99
295
21
271
315
36
35
232
99
234
203
99
221
69
35
99
25
269
99
33
99
99
40
237
33
35
186
40
164
99
99
154
38
195
24
88
256
50
186
35
105
7
302
99
99
36
99
310
28
25
43
30
116
99
256
99
122
99
99
112
83
25
99
99
34
242
82
167
37
185
287
28
145
77
158
99
34
41
22
99
23
99
33
198
137
29
99
37
99
99
99
25
99
76
21
99
205
40
99
99
35
269
99
99
99
99
73
99
99
36
188
174
171
49
168
49
99
33
294
216
99
32
99
35
174
21
49
127
49
99
215
38
99
32
18
34
99
42
99
197
36
260
99
99
136
99
99
81
99
99
206
99
36
196
55
99
99
34
221
35
26
7
20
99
111
99
99
63
176
211
99
32
19
97
146
103
109
21
99
215
99
24
226
35
99
35
35
200
149
222
327
98
148
38
99
99
96
247
108
47
99
222
146
99
205
49
99
225
26
331
99
315
21
36
40
99
99
99
50
24
109
271
99
314
24
259
99
24
249
167
98
167
179
35
178
99
99
157
32
36
99
327
99
99
101
99
143
25
118
25
304
99
329
99
240
252
57
27
310
123
31
250
43
184
99
112
150
38
332
24
99
75
35
224
46
100
31
148
29
99
155
139
36
36
108
36
27
29
311
159
34
99
181
305
99
174
35
167
238
99
56
99
95
256
99
99
32
99
220
49
303
202
137
318
126
112
195
35
19
207
35
99
30
198
99
35
99
313
290
231
239
88
99
99
265
41
36
99
42
214
232
43
108
176
99
86
262
35
310
51
99
148
35
99
98
99
276
26
255
99
99
33
99
20
205
35
25
41
98
99
325
99
36
34
99
150
79
26
91
114
67
35
99
99
99
93
49
28
99
312
189
40
34
66
35
35
23
103
36
19
99
34
235
194
99
24
181
99
36
191
20
26
99
29
99
99
99
21
99
99
90
99
64
170
99
34
99
25
99
99
36
305
164
79
319
98
32
99
99
24
99
70
72
30
99
99
99
43
99
107
99
99
296
207
148
123
308
100
23
74
99
148
99
33
212
28
99
165
46
69
99
99
50
119
99
183
20
99
99
38
27
229
99
48
298
30
99
273
40
36
156
250
315
100
28
99
50
38
99
141
99
231
36
166
35
99
320
185
99
205
171
135
49
34
66
220
68
303
112
99
49
99
197
80
17
285
36
248
99
15
240
35
99
99
99
99
93
49
21
315
128
40
106
189
266
35
50
35
262
99
179
200
42
100
20
133
23
43
319
99
83
305
216
44
99
36
33
99
99
283
271
35
231
282
265
99
179
35
99
99
99
45
98
147
99
50
99
36
226
305
46
25
25
173
308
99
25
99
99
19
110
80
234
99
99
86
99
20
32
95
99
21
99
32
99
36
138
99
6
276
36
99
101
97
35
99
36
33
24
25
35
34
118
212
99
110
90
26
234
35
204
99
88
34
46
99
99
324
139
98
29
99
240
42
290
235
49
297
28
99
99
189
274
19
99
99
98
26
265
21
99
296
239
165
25
99
35
316
23
99
99
39
253
99
176
277
220
39
99
185
142
38
99
99
297
184
135
216
120
250
16
99
99
35
178
99
207
194
99
209
314
146
90
34
122
186
132
99
99
18
49
58
37
99
35
187
111
99
36
21
116
178
17
166
35
38
49
99
36
145
99
129
99
261
189
130
31
150
303
152
271
187
99
99
99
24
186
17
134
99
27
24
31
185
32
318
114
99
58
102
90
26
249
72
22
99
99
32
99
35
177
43
200
19
332
155
99
37
83
146
109
36
98
36
99
125
148
166
26
35
45
242
35
247
315
34
97
99
52
99
102
99
33
123
43
45
99
24
99
255
274
101
30
175
49
99
99
35
110
99
24
191
22
159
178
21
34
237
36
317
241
113
107
28
99
133
37
33
99
29
239
99
148
35
99
99
37
49
99
99
40
99
99
39
28
270
259
32
99
102
19
99
99
52
99
92
99
84
99
185
112
198
20
99
285
111
34
261
34
220
99
332
99
99
313
41
45
24
34
205
99
210
235
249
99
99
322
99
99
112
320
33
99
133
99
99
84
46
36
99
99
241
58
99
48
48
119
36
34
99
100
191
99
100
99
99
99
99
280
99
99
232
28
99
315
99
256
35
170
99
69
99
236
316
105
227
216
19
51
68
319
43
310
244
99
286
232
37
99
99
153
99
34
120
99
99
93
99
38
95
99
36
23
99
99
99
261
99
99
99
114
99
206
99
99
190
124
24
26
99
158
35
99
179
27
205
99
96
93
22
99
256
301
99
331
24
329
99
118
149
123
252
99
99
85
110
226
103
164
194
99
222
169
35
154
101
43
99
99
53
283
21
310
99
292
24
99
99
99
35
54
26
49
43
67
281
253
173
99
26
224
325
99
231
99
24
330
90
272
99
99
275
132
134
274
99
45
40
35
205
25
198
22
201
227
29
35
25
145
176
181
34
99
237
37
99
156
99
51
35
59
212
36
110
264
44
25
22
29
45
331
99
99
99
88
22
99
99
99
99
181
99
110
28
65
142
99
140
99
292
292
99
304
43
46
144
302
283
24
231
309
46
21
99
29
195
37
91
101
34
33
294
169
39
99
121
45
99
312
99
211
304
254
63
150
249
37
136
99
23
197
284
146
332
99
99
168
241
99
99
26
37
187
161
36
324
99
39
225
99
98
30
147
99
202
319
199
180
99
210
119
99
20
99
205
161
25
215
99
57
276
31
327
249
25
34
99
106
99
99
99
332
99
33
162
226
172
27
92
99
134
99
296
99
307
36
99
78
99
47
100
36
204
33
241
99
274
218
25
319
49
34
35
135
34
99
99
27
289
219
99
199
178
176
99
56
99
277
292
195
99
185
134
50
287
115
156
34
22
25
245
27
35
99
69
99
144
99
235
246
42
25
311
99
99
99
24
119
99
36
34
99
54
99
35
296
99
49
22
310
34
261
35
182
39
100
36
34
333
37
99
230
240
99
174
35
94
41
35
107
162
127
248
145
282
45
28
275
271
333
250
36
34
99
25
24
33
39
36
268
99
205
98
99
107
117
300
99
107
99
35
99
181
99
36
306
100
99
45
284
36
196
99
301
36
90
31
177
148
99
24
99
91
49
201
174
287
112
35
99
82
99
99
99
107
99
99
99
217
239
25
99
39
99
264
20
99
99
330
99
264
259
185
99
99
36
99
28
36
99
320
36
20
142
179
135
230
99
317
99
285
241
108
19
99
99
19
296
113
314
99
99
81
91
188
34
99
84
43
49
99
45
99
162
45
99
318
148
28
25
48
158
317
145
244
46
48
272
235
188
41
99
99
99
259
172
99
97
108
160
120
277
99
81
99
37
246
99
289
99
99
193
37
19
271
323
23
50
161
99
27
261
99
69
99
24
99
152
99
322
239
99
99
23
99
39
324
83
106
46
288
99
38
79
99
34
99
99
229
36
93
99
223
29
28
26
44
262
175
303
225
114
99
223
99
148
99
24
99
30
116
316
29
99
83
198
201
19
99
216
187
34
202
36
145
99
172
35
191
25
161
20
313
196
99
310
270
88
96
141
314
99
49
36
143
132
99
158
112
99
160
294
100
26
311
327
151
193
25
115
170
35
118
23
40
40
28
27
244
248
251
114
99
99
99
21
25
225
25
191
24
64
99
48
196
100
114
99
99
183
135
334
21
55
129
209
99
21
32
30
21
36
99
28
257
126
99
20
139
97
316
99
99
147
99
99
36
99
36
99
332
99
48
99
279
152
99
29
185
30
99
99
112
131
315
264
102
99
25
317
297
123
99
192
94
83
252
27
99
34
310
94
270
99
99
146
42
42
24
99
99
36
22
274
99
99
77
99
91
44
99
176
259
303
284
184
198
23
258
218
168
99
167
241
235
184
99
66
294
320
149
99
315
232
36
99
180
327
117
99
29
161
99
28
24
99
99
181
115
99
49
273
96
307
176
99
34
59
117
180
273
99
277
99
107
236
237
99
99
77
23
22
35
43
115
181
328
99
217
35
99
27
160
87
297
35
173
104
223
190
225
99
99
91
30
239
99
24
99
166
34
105
276
99
29
271
113
36
28
24
44
234
79
24
99
36
40
87
36
199
209
99
25
24
186
141
97
26
52
322
19
99
67
102
22
121
48
99
319
99
47
37
22
29
36
171
199
91
34
31
199
231
48
99
137
99
155
99
32
140
27
147
192
26
99
99
99
159
27
36
258
35
99
34
313
99
25
99
123
273
176
140
106
249
99
99
37
32
35
94
99
29
32
115
99
271
307
35
34
140
224
99
294
196
99
202
99
288
323
33
196
44
271
12
45
99
36
55
216
99
185
190
36
317
12
35
44
332
253
213
162
99
116
116
126
99
105
99
164
99
99
49
25
149
25
29
42
281
311
99
129
28
183
34
99
178
104
100
99
185
203
320
27
99
99
99
208
99
36
49
99
99
109
99
314
99
99
300
36
32
23
252
176
40
36
99
220
152
68
99
41
33
146
160
99
21
99
99
213
20
29
37
36
71
99
184
21
156
99
332
219
25
230
151
172
179
99
274
39
24
64
99
28
93
36
24
73
72
239
301
53
23
98
34
99
36
99
104
268
27
99
214
99
319
35
36
33
160
282
99
31
99
37
148
99
29
142
32
135
27
205
266
98
99
318
24
152
32
99
99
99
234
329
27
99
153
26
24
30
275
99
66
272
223
147
222
97
99
28
322
139
99
99
252
161
233
99
35
99
178
292
99
66
39
80
122
44
233
310
165
36
99
99
302
77
178
298
99
193
256
99
132
316
32
99
44
312
313
101
99
55
99
45
99
116
99
64
99
99
36
25
36
112
99
205
34
267
317
214
26
29
99
188
99
292
101
99
196
24
34
228
191
75
213
99
93
31
228
97
35
251
99
279
99
20
332
21
26
99
99
71
99
99
34
24
79
99
241
155
100
99
99
110
218
99
110
27
99
175
21
254
99
265
99
95
112
30
27
196
32
332
99
106
273
210
35
214
57
24
31
319
319
210
99
97
99
36
253
220
99
289
24
237
34
99
39
191
29
314
314
44
45
321
204
197
36
99
99
45
233
37
33
331
99
20
36
179
30
99
43
24
99
24
270
276
37
45
30
99
103
99
97
99
201
36
168
87
34
99
31
99
30
36
39
36
99
142
36
283
49
187
99
99
99
186
33
99
100
35
183
227
99
40
40
55
35
32
308
24
40
37
223
34
146
214
241
259
312
109
206
114
99
256
110
324
188
187
99
36
99
99
238
36
291
45
50
242
99
94
99
252
58
323
220
294
112
99
43
99
123
265
47
84
99
99
35
154
99
235
99
99
90
40
103
233
303
261
35
34
99
99
133
222
91
237
164
49
99
146
210
99
145
31
317
99
99
273
99
37
185
99
295
99
28
271
99
290
23
50
30
209
268
22
32
101
45
156
24
252
34
44
247
208
99
20
94
99
323
141
29
25
47
99
261
298
240
99
27
150
219
238
33
170
163
24
298
135
157
26
35
99
235
284
24
25
36
37
35
46
99
21
99
104
159
36
109
294
99
48
24
99
42
99
39
100
178
20
99
305
216
99
166
149
89
20
36
99
34
42
20
98
210
81
36
100
230
253
251
91
35
88
32
289
99
25
30
25
155
118
99
91
99
99
111
29
182
99
36
286
36
26
34
99
36
99
110
201
225
99
25
237
316
97
51
53
71
221
24
29
250
174
99
64
99
165
326
99
286
203
179
99
186
164
288
99
99
204
324
184
132
278
69
99
35
113
260
153
287
231
99
283
38
99
313
149
174
228
311
99
99
21
19
299
99
99
207
209
312
210
192
78
90
174
34
179
299
253
324
99
99
30
235
328
99
37
90
99
152
164
106
140
33
284
64
99
48
322
22
47
99
184
123
282
260
167
99
29
99
276
37
99
286
99
30
175
265
150
294
204
32
99
99
99
320
175
91
61
26
36
87
315
156
99
69
101
99
313
190
31
189
68
289
229
313
127
316
289
45
147
197
110
331
255
21
36
32
34
99
306
114
313
36
99
168
99
162
99
99
241
99
99
229
283
99
99
64
99
304
60
99
170
38
258
24
26
40
112
198
35
99
328
135
282
219
37
108
49
99
24
308
52
99
99
99
31
175
45
60
35
99
256
99
207
266
220
279
19
289
27
35
99
36
38
234
36
24
99
119
99
99
99
37
180
55
198
124
241
25
43
100
245
49
99
99
34
313
36
137
28
99
77
311
167
228
147
107
266
176
99
155
258
34
97
46
98
151
99
251
109
36
15
164
99
99
188
189
130
23
99
99
214
99
333
212
271
59
99
142
191
25
277
42
99
46
24
226
78
37
99
99
33
99
309
227
283
41
99
65
99
99
36
326
248
196
30
99
66
27
51
225
34
154
136
187
99
163
94
54
23
204
99
27
312
183
35
99
99
35
236
49
151
167
281
99
216
150
27
331
64
255
254
99
99
29
204
180
99
99
36
20
236
99
45
99
329
95
20
24
152
46
186
29
239
22
178
99
26
293
281
34
213
24
145
210
254
25
138
99
37
315
99
229
210
131
99
295
99
167
99
99
259
164
99
28
34
255
99
243
329
152
47
21
167
11
44
167
27
99
192
99
178
323
99
35
199
175
174
99
35
293
59
26
99
49
283
99
291
218
99
269
99
160
99
162
99
268
31
85
46
21
81
99
99
99
152
99
115
36
33
99
333
21
43
99
96
99
147
91
99
130
301
99
34
20
159
22
179
21
277
157
32
41
123
160
26
303
32
167
226
7
100
274
127
218
26
97
25
99
158
35
99
99
205
227
35
251
184
99
35
331
274
99
115
258
210
99
101
99
35
99
305
297
171
163
215
99
163
62
107
25
204
205
32
254
70
24
294
49
99
99
147
99
226
99
99
241
28
190
99
46
99
99
99
66
99
35
31
192
99
89
239
99
193
99
99
169
94
240
91
24
99
31
205
185
49
99
299
99
325
99
99
112
91
42
300
41
88
318
34
55
99
23
329
35
43
316
99
116
99
32
201
238
99
99
22
183
208
24
36
264
281
287
150
246
99
299
99
99
99
241
250
277
302
99
279
43
99
291
251
147
99
51
247
318
99
96
259
262
134
96
143
99
99
99
99
79
99
99
100
56
40
301
99
99
54
49
115
296
328
100
99
234
324
314
176
246
99
182
167
99
99
49
237
150
23
154
36
25
99
99
67
169
99
99
17
99
99
35
114
99
155
45
180
20
146
99
40
80
32
132
99
308
108
31
225
41
28
199
265
242
55
146
21
33
172
259
35
49

In [17]:
# class PreparationData():
    # divide_in_codons(train_df)

In [ ]:
select_columns = ['prefix',
       'w_lenght_0', 'w_lenght_1', 'w_lenght_2', 'w_lenght_3', 'w_lenght_4',
       'w_lenght_5', 'w_lenght_6', 'w_lenght_7', 'w_lenght_8', 'w_lenght_9',
       'w_lenght_10', 'w_lenght_11', 'w_lenght_12', 'w_lenght_13',
       'w_lenght_14', 'NucleotideSequence']

In [22]:
X_train =  train_df[select_columns]
y_train  = train_df["Description"]